version: '3.8'

services:
  # Service Laravel (PHP-FPM disarankan untuk produksi/nginx)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network
    tmpfs:
      - /tmp
    # Jika menggunakan Dockerfile standar, entrypoint biasanya php-fpm
    # Namun jika ingin menjalankan server artisan langsung:
    # command: php artisan serve --host=0.0.0.0 --port=8000

  # Service Nginx (Sebagai Reverse Proxy)
  nginx:
    image: public.ecr.aws/nginx/nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  # Service Database (MySQL)
  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: "1010"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db-data:
